//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.08 at 05:12:42 AM PDT 
//


package gov.nih.nci.evs.cdisc.report.xml;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ODMContext.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ODMContext">
 *   &lt;restriction base="{http://www.cdisc.org/ns/odm/v1.3}text">
 *     &lt;enumeration value="Submission"/>
 *     &lt;enumeration value="Other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ODMContext", namespace = "http://ncicb.nci.nih.gov/xml/odm/EVS/CDISC")
@XmlEnum
public enum ODMContext {

    @XmlEnumValue("Submission")
    SUBMISSION("Submission"),
    @XmlEnumValue("Other")
    OTHER("Other");
    private final String value;

    ODMContext(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ODMContext fromValue(String v) {
        for (ODMContext c: ODMContext.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
