//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.05.08 at 05:12:42 AM PDT
//

@jakarta.xml.bind.annotation.XmlSchema(
    namespace = "http://www.cdisc.org/ns/odm/v1.3",
    elementFormDefault = XmlNsForm.QUALIFIED,
    xmlns = {
      @XmlNs(prefix = "nciodm", namespaceURI = "http://ncicb.nci.nih.gov/xml/odm/EVS/CDISC"),
      @XmlNs(prefix = "", namespaceURI = "http://www.cdisc.org/ns/odm/v1.3")
    })
package gov.nih.nci.evs.cdisc.report.xml;

import jakarta.xml.bind.annotation.XmlNs;
import jakarta.xml.bind.annotation.XmlNsForm;
