package gov.nih.nci.evs.cdisc.report.aws;

import com.amazonaws.services.lambda.runtime.Context;
import com.amazonaws.services.lambda.runtime.RequestHandler;
import gov.nih.nci.evs.cdisc.report.IchRDFGenerator;
import gov.nih.nci.evs.cdisc.report.OwlZipFileGenerator;
import gov.nih.nci.evs.cdisc.report.RDFGenerator;
import gov.nih.nci.evs.cdisc.report.ReportEnum;
import gov.nih.nci.evs.cdisc.report.model.ReportDetail;
import gov.nih.nci.evs.cdisc.report.model.ReportSummary;
import gov.nih.nci.evs.cdisc.report.utils.AssertUtils;
import gov.nih.nci.evs.cdisc.report.utils.ReportUtils;
import java.io.File;
import org.apache.commons.io.FilenameUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class LambdaHandler implements RequestHandler<ReportSummary, ReportSummary> {
  Logger log = LoggerFactory.getLogger(LambdaHandler.class);

  /**
   * Generate OWL files from ODM XML files generated by odm-report
   *
   * @param input contains path to ODM XML files generated by odm-report
   * @param context lambda context
   * @return augmented report list with the generated OWL files
   */
  @Override
  public ReportSummary handleRequest(ReportSummary input, Context context) {
    validate(input);
    for (ReportDetail reportDetail : input.getReportDetails()) {
      String textFile = reportDetail.getReports().get(ReportEnum.MAIN_TEXT);
      if (textFile != null && new File(textFile).exists()) {
        String baseName = FilenameUtils.removeExtension(textFile);
        String owlFile = baseName + ".owl";
        if (owlFile.toLowerCase().contains("ich")) {
          log.info("Using ICH RDF generator");
          IchRDFGenerator rdfGenerator = new IchRDFGenerator();
          rdfGenerator.generate(textFile, owlFile);
        } else {
          log.info("Using CDISC RDF generator");
          RDFGenerator rdfGenerator = new RDFGenerator();
          rdfGenerator.generate(textFile, owlFile);
        }

        OwlZipFileGenerator owlZipFileGenerator =
            new OwlZipFileGenerator(ReportUtils.getStaticFilesPath());
        File owlZipFile = owlZipFileGenerator.generateOwlZipFile(new File(owlFile));
        reportDetail.getReports().put(ReportEnum.MAIN_OWL, owlFile);
        reportDetail.getReports().put(ReportEnum.OWL_ZIP, owlZipFile.getAbsolutePath());
      } else {
        throw new RuntimeException(String.format("File %s does not exist.", textFile));
      }
    }
    // The Excel file report gets formatted in place, so
    return input;
  }

  private void validate(ReportSummary request) {
    AssertUtils.assertRequired(request.getReportDetails(), "reportDetails");
    AssertUtils.assertRequired(request.getPublicationDate(), "publicationDate");
  }
}
