//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.11 at 05:09:46 AM PDT 
//


package gov.nih.nci.evs.cdisc.report.xml;


import jakarta.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the gov.nih.nci.evs.cdisc.report.xml package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: gov.nih.nci.evs.cdisc.report.xml
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Ontology }
     * 
     */
    public Ontology createOntology() {
        return new Ontology();
    }

    /**
     * Create an instance of {@link PermissibleValue }
     * 
     */
    public PermissibleValue createPermissibleValue() {
        return new PermissibleValue();
    }

    /**
     * Create an instance of {@link PermissibleValue.InValueDomain }
     * 
     */
    public PermissibleValue.InValueDomain createPermissibleValueInValueDomain() {
        return new PermissibleValue.InValueDomain();
    }

    /**
     * Create an instance of {@link RDF }
     * 
     */
    public RDF createRDF() {
        return new RDF();
    }

    /**
     * Create an instance of {@link Ontology.Imports }
     * 
     */
    public Ontology.Imports createOntologyImports() {
        return new Ontology.Imports();
    }

    /**
     * Create an instance of {@link Ontology.VersionInfo }
     * 
     */
    public Ontology.VersionInfo createOntologyVersionInfo() {
        return new Ontology.VersionInfo();
    }

    /**
     * Create an instance of {@link NciPreferredTerm }
     * 
     */
    public NciPreferredTerm createNciPreferredTerm() {
        return new NciPreferredTerm();
    }

    /**
     * Create an instance of {@link NciCode }
     * 
     */
    public NciCode createNciCode() {
        return new NciCode();
    }

    /**
     * Create an instance of {@link CdiscDefinition }
     * 
     */
    public CdiscDefinition createCdiscDefinition() {
        return new CdiscDefinition();
    }

    /**
     * Create an instance of {@link CdiscSynonyms }
     * 
     */
    public CdiscSynonyms createCdiscSynonyms() {
        return new CdiscSynonyms();
    }

    /**
     * Create an instance of {@link CdiscSubmissionValue }
     * 
     */
    public CdiscSubmissionValue createCdiscSubmissionValue() {
        return new CdiscSubmissionValue();
    }

    /**
     * Create an instance of {@link CodelistName }
     * 
     */
    public CodelistName createCodelistName() {
        return new CodelistName();
    }

    /**
     * Create an instance of {@link IsExtensibleCodelist }
     * 
     */
    public IsExtensibleCodelist createIsExtensibleCodelist() {
        return new IsExtensibleCodelist();
    }

    /**
     * Create an instance of {@link PermissibleValue.InValueDomain.EnumeratedValueDomain }
     * 
     */
    public PermissibleValue.InValueDomain.EnumeratedValueDomain createPermissibleValueInValueDomainEnumeratedValueDomain() {
        return new PermissibleValue.InValueDomain.EnumeratedValueDomain();
    }

}
