//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference
// Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2023.05.11 at 05:09:46 AM PDT
//

@jakarta.xml.bind.annotation.XmlSchema(
    namespace = "http://rdf.cdisc.org/ct/schema#",
    xmlns = {
      @XmlNs(prefix = "", namespaceURI = "http://rdf.cdisc.org/{terminology}-terminology"),
      @XmlNs(prefix = "mms", namespaceURI = "http://rdf.cdisc.org/mms#"),
      @XmlNs(prefix = "rdf", namespaceURI = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"),
      @XmlNs(prefix = "owl", namespaceURI = "http://www.w3.org/2002/07/owl#"),
      @XmlNs(prefix = "xsd", namespaceURI = "http://www.w3.org/2001/XMLSchema#"),
      @XmlNs(prefix = "cts", namespaceURI = "http://rdf.cdisc.org/ct/schema#"),
      @XmlNs(prefix = "rdfs", namespaceURI = "http://www.w3.org/2000/01/rdf-schema#")
    },
    elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package gov.nih.nci.evs.cdisc.report.xml;

import jakarta.xml.bind.annotation.XmlNs;