//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.11 at 05:09:46 AM PDT 
//


package gov.nih.nci.evs.cdisc.report.xml;

import jakarta.xml.bind.annotation.*;

/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="inValueDomain">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence minOccurs="0">
 *                   &lt;element name="EnumeratedValueDomain">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element ref="{http://rdf.cdisc.org/ct/schema#}cdiscDefinition"/>
 *                             &lt;element ref="{http://rdf.cdisc.org/ct/schema#}nciPreferredTerm"/>
 *                             &lt;element ref="{http://rdf.cdisc.org/ct/schema#}nciCode"/>
 *                             &lt;element ref="{http://rdf.cdisc.org/ct/schema#}cdiscSynonyms"/>
 *                             &lt;element ref="{http://rdf.cdisc.org/ct/schema#}cdiscSubmissionValue"/>
 *                             &lt;element ref="{http://rdf.cdisc.org/ct/schema#}codelistName"/>
 *                             &lt;element ref="{http://rdf.cdisc.org/ct/schema#}isExtensibleCodelist"/>
 *                           &lt;/sequence>
 *                           &lt;attribute ref="{http://www.w3.org/1999/02/22-rdf-syntax-ns#}ID use="required""/>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute ref="{http://www.w3.org/1999/02/22-rdf-syntax-ns#}resource"/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element ref="{http://rdf.cdisc.org/ct/schema#}nciPreferredTerm"/>
 *         &lt;element ref="{http://rdf.cdisc.org/ct/schema#}nciCode"/>
 *         &lt;element ref="{http://rdf.cdisc.org/ct/schema#}cdiscDefinition"/>
 *         &lt;element ref="{http://rdf.cdisc.org/ct/schema#}cdiscSynonyms" minOccurs="0"/>
 *         &lt;element ref="{http://rdf.cdisc.org/ct/schema#}cdiscSubmissionValue"/>
 *       &lt;/sequence>
 *       &lt;attribute ref="{http://www.w3.org/1999/02/22-rdf-syntax-ns#}ID use="required""/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "inValueDomain",
    "nciPreferredTerm",
    "nciCode",
    "cdiscDefinition",
    "cdiscSynonyms",
    "cdiscSubmissionValue"
})
@XmlRootElement(name = "PermissibleValue", namespace = "http://rdf.cdisc.org/mms#")
public class PermissibleValue {

    @XmlElement(namespace = "http://rdf.cdisc.org/mms#", required = true)
    protected PermissibleValue.InValueDomain inValueDomain;
    @XmlElement(required = true)
    protected NciPreferredTerm nciPreferredTerm;
    @XmlElement(required = true)
    protected NciCode nciCode;
    @XmlElement(required = true)
    protected CdiscDefinition cdiscDefinition;
    protected CdiscSynonyms cdiscSynonyms;
    @XmlElement(required = true)
    protected CdiscSubmissionValue cdiscSubmissionValue;
    @XmlAttribute(name = "ID", namespace = "http://www.w3.org/1999/02/22-rdf-syntax-ns#", required = true)
    protected String id;

    /**
     * Gets the value of the inValueDomain property.
     * 
     * @return
     *     possible object is
     *     {@link InValueDomain }
     *     
     */
    public InValueDomain getInValueDomain() {
        return inValueDomain;
    }

    /**
     * Sets the value of the inValueDomain property.
     * 
     * @param value
     *     allowed object is
     *     {@link InValueDomain }
     *     
     */
    public void setInValueDomain(InValueDomain value) {
        this.inValueDomain = value;
    }

    /**
     * Gets the value of the nciPreferredTerm property.
     * 
     * @return
     *     possible object is
     *     {@link NciPreferredTerm }
     *     
     */
    public NciPreferredTerm getNciPreferredTerm() {
        return nciPreferredTerm;
    }

    /**
     * Sets the value of the nciPreferredTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link NciPreferredTerm }
     *     
     */
    public void setNciPreferredTerm(NciPreferredTerm value) {
        this.nciPreferredTerm = value;
    }

    /**
     * Gets the value of the nciCode property.
     * 
     * @return
     *     possible object is
     *     {@link NciCode }
     *     
     */
    public NciCode getNciCode() {
        return nciCode;
    }

    /**
     * Sets the value of the nciCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link NciCode }
     *     
     */
    public void setNciCode(NciCode value) {
        this.nciCode = value;
    }

    /**
     * Gets the value of the cdiscDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link CdiscDefinition }
     *     
     */
    public CdiscDefinition getCdiscDefinition() {
        return cdiscDefinition;
    }

    /**
     * Sets the value of the cdiscDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link CdiscDefinition }
     *     
     */
    public void setCdiscDefinition(CdiscDefinition value) {
        this.cdiscDefinition = value;
    }

    /**
     * Gets the value of the cdiscSynonyms property.
     * 
     * @return
     *     possible object is
     *     {@link CdiscSynonyms }
     *     
     */
    public CdiscSynonyms getCdiscSynonyms() {
        return cdiscSynonyms;
    }

    /**
     * Sets the value of the cdiscSynonyms property.
     * 
     * @param value
     *     allowed object is
     *     {@link CdiscSynonyms }
     *     
     */
    public void setCdiscSynonyms(CdiscSynonyms value) {
        this.cdiscSynonyms = value;
    }

    /**
     * Gets the value of the cdiscSubmissionValue property.
     * 
     * @return
     *     possible object is
     *     {@link CdiscSubmissionValue }
     *     
     */
    public CdiscSubmissionValue getCdiscSubmissionValue() {
        return cdiscSubmissionValue;
    }

    /**
     * Sets the value of the cdiscSubmissionValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link CdiscSubmissionValue }
     *     
     */
    public void setCdiscSubmissionValue(CdiscSubmissionValue value) {
        this.cdiscSubmissionValue = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence minOccurs="0">
     *         &lt;element name="EnumeratedValueDomain">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element ref="{http://rdf.cdisc.org/ct/schema#}cdiscDefinition"/>
     *                   &lt;element ref="{http://rdf.cdisc.org/ct/schema#}nciPreferredTerm"/>
     *                   &lt;element ref="{http://rdf.cdisc.org/ct/schema#}nciCode"/>
     *                   &lt;element ref="{http://rdf.cdisc.org/ct/schema#}cdiscSynonyms"/>
     *                   &lt;element ref="{http://rdf.cdisc.org/ct/schema#}cdiscSubmissionValue"/>
     *                   &lt;element ref="{http://rdf.cdisc.org/ct/schema#}codelistName"/>
     *                   &lt;element ref="{http://rdf.cdisc.org/ct/schema#}isExtensibleCodelist"/>
     *                 &lt;/sequence>
     *                 &lt;attribute ref="{http://www.w3.org/1999/02/22-rdf-syntax-ns#}ID use="required""/>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute ref="{http://www.w3.org/1999/02/22-rdf-syntax-ns#}resource"/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "enumeratedValueDomain"
    })
    public static class InValueDomain {

        @XmlElement(name = "EnumeratedValueDomain", namespace = "http://rdf.cdisc.org/mms#")
        protected PermissibleValue.InValueDomain.EnumeratedValueDomain enumeratedValueDomain;
        @XmlAttribute(name = "resource", namespace = "http://www.w3.org/1999/02/22-rdf-syntax-ns#")
        protected String resource;

        /**
         * Gets the value of the enumeratedValueDomain property.
         * 
         * @return
         *     possible object is
         *     {@link EnumeratedValueDomain }
         *     
         */
        public EnumeratedValueDomain getEnumeratedValueDomain() {
            return enumeratedValueDomain;
        }

        /**
         * Sets the value of the enumeratedValueDomain property.
         * 
         * @param value
         *     allowed object is
         *     {@link EnumeratedValueDomain }
         *     
         */
        public void setEnumeratedValueDomain(EnumeratedValueDomain value) {
            this.enumeratedValueDomain = value;
        }

        /**
         * Gets the value of the resource property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResource() {
            return resource;
        }

        /**
         * Sets the value of the resource property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResource(String value) {
            this.resource = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element ref="{http://rdf.cdisc.org/ct/schema#}cdiscDefinition"/>
         *         &lt;element ref="{http://rdf.cdisc.org/ct/schema#}nciPreferredTerm"/>
         *         &lt;element ref="{http://rdf.cdisc.org/ct/schema#}nciCode"/>
         *         &lt;element ref="{http://rdf.cdisc.org/ct/schema#}cdiscSynonyms"/>
         *         &lt;element ref="{http://rdf.cdisc.org/ct/schema#}cdiscSubmissionValue"/>
         *         &lt;element ref="{http://rdf.cdisc.org/ct/schema#}codelistName"/>
         *         &lt;element ref="{http://rdf.cdisc.org/ct/schema#}isExtensibleCodelist"/>
         *       &lt;/sequence>
         *       &lt;attribute ref="{http://www.w3.org/1999/02/22-rdf-syntax-ns#}ID use="required""/>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "cdiscDefinition",
            "nciPreferredTerm",
            "nciCode",
            "cdiscSynonyms",
            "cdiscSubmissionValue",
            "codelistName",
            "isExtensibleCodelist"
        })
        public static class EnumeratedValueDomain {

            @XmlElement(required = true)
            protected CdiscDefinition cdiscDefinition;
            @XmlElement(required = true)
            protected NciPreferredTerm nciPreferredTerm;
            @XmlElement(required = true)
            protected NciCode nciCode;
            @XmlElement(required = true)
            protected CdiscSynonyms cdiscSynonyms;
            @XmlElement(required = true)
            protected CdiscSubmissionValue cdiscSubmissionValue;
            @XmlElement(required = true)
            protected CodelistName codelistName;
            @XmlElement(required = true)
            protected IsExtensibleCodelist isExtensibleCodelist;
            @XmlAttribute(name = "ID", namespace = "http://www.w3.org/1999/02/22-rdf-syntax-ns#", required = true)
            protected String id;

            /**
             * Gets the value of the cdiscDefinition property.
             * 
             * @return
             *     possible object is
             *     {@link CdiscDefinition }
             *     
             */
            public CdiscDefinition getCdiscDefinition() {
                return cdiscDefinition;
            }

            /**
             * Sets the value of the cdiscDefinition property.
             * 
             * @param value
             *     allowed object is
             *     {@link CdiscDefinition }
             *     
             */
            public void setCdiscDefinition(CdiscDefinition value) {
                this.cdiscDefinition = value;
            }

            /**
             * Gets the value of the nciPreferredTerm property.
             * 
             * @return
             *     possible object is
             *     {@link NciPreferredTerm }
             *     
             */
            public NciPreferredTerm getNciPreferredTerm() {
                return nciPreferredTerm;
            }

            /**
             * Sets the value of the nciPreferredTerm property.
             * 
             * @param value
             *     allowed object is
             *     {@link NciPreferredTerm }
             *     
             */
            public void setNciPreferredTerm(NciPreferredTerm value) {
                this.nciPreferredTerm = value;
            }

            /**
             * Gets the value of the nciCode property.
             * 
             * @return
             *     possible object is
             *     {@link NciCode }
             *     
             */
            public NciCode getNciCode() {
                return nciCode;
            }

            /**
             * Sets the value of the nciCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link NciCode }
             *     
             */
            public void setNciCode(NciCode value) {
                this.nciCode = value;
            }

            /**
             * Gets the value of the cdiscSynonyms property.
             * 
             * @return
             *     possible object is
             *     {@link CdiscSynonyms }
             *     
             */
            public CdiscSynonyms getCdiscSynonyms() {
                return cdiscSynonyms;
            }

            /**
             * Sets the value of the cdiscSynonyms property.
             * 
             * @param value
             *     allowed object is
             *     {@link CdiscSynonyms }
             *     
             */
            public void setCdiscSynonyms(CdiscSynonyms value) {
                this.cdiscSynonyms = value;
            }

            /**
             * Gets the value of the cdiscSubmissionValue property.
             * 
             * @return
             *     possible object is
             *     {@link CdiscSubmissionValue }
             *     
             */
            public CdiscSubmissionValue getCdiscSubmissionValue() {
                return cdiscSubmissionValue;
            }

            /**
             * Sets the value of the cdiscSubmissionValue property.
             * 
             * @param value
             *     allowed object is
             *     {@link CdiscSubmissionValue }
             *     
             */
            public void setCdiscSubmissionValue(CdiscSubmissionValue value) {
                this.cdiscSubmissionValue = value;
            }

            /**
             * Gets the value of the codelistName property.
             * 
             * @return
             *     possible object is
             *     {@link CodelistName }
             *     
             */
            public CodelistName getCodelistName() {
                return codelistName;
            }

            /**
             * Sets the value of the codelistName property.
             * 
             * @param value
             *     allowed object is
             *     {@link CodelistName }
             *     
             */
            public void setCodelistName(CodelistName value) {
                this.codelistName = value;
            }

            /**
             * Gets the value of the isExtensibleCodelist property.
             * 
             * @return
             *     possible object is
             *     {@link IsExtensibleCodelist }
             *     
             */
            public IsExtensibleCodelist getIsExtensibleCodelist() {
                return isExtensibleCodelist;
            }

            /**
             * Sets the value of the isExtensibleCodelist property.
             * 
             * @param value
             *     allowed object is
             *     {@link IsExtensibleCodelist }
             *     
             */
            public void setIsExtensibleCodelist(IsExtensibleCodelist value) {
                this.isExtensibleCodelist = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getID() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setID(String value) {
                this.id = value;
            }

        }

    }

}
